baseURL = 'https://example.org/'
languageCode = 'zh-CN'
title = '我的技术博客'

[outputs]
  home = ["HTML", "JSON"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[params]
  description = "分享技术见解、编程经验与生活感悟"
  author = "Hugo Theme Huxulm"
  
  # 首页最新博文数量（可配置）
  recentPostsCount = 3
  
  # 动画背景配置
  [params.animatedBackground]
    enable = true
    homeOnly = false
    # 动画类型: "particles" | "waves" | "gradient" | "none"
    type = "particles"

[build]
  writeStats = true
  
  [build.buildStats]
    enable = true
  
  [[build.cachebusters]]
    source = 'hugo_stats\.json'
    target = 'css'
  
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
  
  [[build.cachebusters]]
    source = 'assets/.*\.(js|ts|jsx|tsx)'
    target = 'js'
  
  [[build.cachebusters]]
    source = '(go|html)$'
    target = 'css'

[module]
  # 挂载 Font Awesome（从主题的 node_modules）
  [[module.mounts]]
    source = "../../node_modules/@fortawesome/fontawesome-free/webfonts"
    target = "static/webfonts"
  
  # 定义主题的挂载点
  [[module.mounts]]
    source = "assets"
    target = "assets"
  
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  
  [[module.mounts]]
    source = "static"
    target = "static"
  
  [[module.mounts]]
    source = "data"
    target = "data"
  
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

  [[module.imports]]
    #path = "github.com/huxulm/hugo-theme-huxulm"
    # 如果是本地开发，可以用相对路径替代：
    path = "../.."    